---
title: "Licence"
toc: false
back-to-top-navigation: false
---

&#169; 2024 -- *Corentin DUCLOUX*   

Le contenu de mon site web est publié sous licence [Creative Commons Attribution 4.0 International (CC BY-NC-SA)](https://creativecommons.org/licenses/by-nc-sa/4.0/){.external target="_blank"}.

{{< fa brands creative-commons size=2x >}} {{< fa brands creative-commons-by size=2x >}} {{< fa brands creative-commons-nc size=2x >}} {{< fa brands creative-commons-sa size=2x >}}

> Vous êtes autorisés à copier, distribuer et communiquer le matériel par tous moyens et sous tous formats. Vous devez créditer l'Œuvre, intégrer un lien vers la licence et indiquer si des modifications ont été effectuées. Vous n'êtes pas autorisé à faire un usage commercial de cette Oeuvre, tout ou partie du matériel la composant. 

## Logiciels utilisés

Le code source ainsi que l'ensemble des fichiers hostés sur mon site web sont disponibles sur {{< fa brands github >}} **GitHub**.

**Icônes** : [{{< fa brands font-awesome >}}](https://fontawesome.com/) [FontAwesome](https://fontawesome.com/){.external target="_blank"}

**Polices** : [{{< fa brands google >}}](https://fonts.google.com/)   [Google Fonts](https://fonts.google.com/){.external target="_blank"}

**Hébergement** : [{{< iconify simple-icons:netlify >}}](https://www.netlify.com/) [Netlify](https://www.netlify.com/){.external target="_blank"}

**Thème** : [https://github.com/robb0wen/synthwave-vscode](https://github.com/robb0wen/synthwave-vscode){.external target="_blank"}

## Autres informations

```{python}
# | label: load_yaml
# | echo: false

import yaml
from typing import Any, Dict
from IPython.display import Markdown


def load_yaml(file_path: str, key: str) -> Dict[str, Any]:
    """
    Read and load a YAML file.

    Args:
        file_path (str): The path to the YAML file to be read.
        key (str): Key of a YAML file.

    Returns:
        Dict[str, Any]: A dictionary representing the contents of the YAML file.

    Raises:
        FileNotFoundError: If the specified file does not exist.
        yaml.YAMLError: If the file contains invalid YAML.
    """
    try:
        with open(file_path, "r", encoding="utf-8") as file:
            data = yaml.safe_load(file)
        return data.get(key)
    except FileNotFoundError as e:
        print(f"Error: {e}")
        raise
    except yaml.YAMLError as e:
        print(f"Error parsing YAML: {e}")
        raise
```

:::{.website-infos}

```{python}
# | label: print_version
# | echo: false

version = load_yaml("utils/version.yml", "version")
Markdown(f"Version {version}")
```

```{python}
# | label: print_date
# | echo: false

date = load_yaml("utils/date.yml", "date")
Markdown(f"Publié le {date}")
```

:::