---
title: "Mon parcours"
smooth-scroll: true
---

::: {.timeline}

::: {.timeline-event}
::: {.timeline-point .bg_2}
:::
::: {.timeline-content}
::: {.timeline-border .bg_2}
:::
::: {.timeline-description}

## {{< fa briefcase >}} Data Engineer (Stage)

{{< fa building >}} **EDF**

{{< fa calendar-days >}} 04/2024 -- 10/2024

{{< fa location-dot >}} *Tours, France*

Développement de *ViZiR*, une application **python** (`streamlit`) de Data Visualisation et de post-traitement de résultats de simulation. Multi-formats et utilisée en production par plus d'une centaine d'ingénieurs, *ViZiR* permet d'analyser à la volée et de manière dynamique les résultats de simulation, tout en permettant une personnalisation sauvegardable poussée $\rightarrow$ **ViZiR facilite les tests de non-régression pour le développement du simulateur EPR2 et contribue à alimenter de nombreuses études au quotidien.**

Développement d'une application {{< fa brands r-project >}} Shiny générant des rapports automatisés sur les impacts fonctionnels et les impacts sûretés liés à la perte d'armoires de contrôle-commande pour l'EPR d'Hinkley Point C $\rightarrow$ **Cet outil a permis d'économiser environ 4400 heures de travail et 330k€, en plus d'améliorer la qualité du livrable final.**

Création de Data Pipelines utilisant `duckdb` et `polars`, `pydantic` pour la Data Validation.

Organisation de présentations et sensibilisation autour des bonnes pratiques de développement sur **python** et R.

[Découvrir mon rapport {{< fa arrow-up-right-from-square >}}](assets/Internship_Report_EDF.pdf){.btn .btn-outline-primary .btn role="button" .center}

:::
:::
:::

::: {.timeline-event}
::: {.timeline-point .bg_3}
:::
::: {.timeline-content}
::: {.timeline-border .bg_3}
:::
::: {.timeline-description}

## {{< fa briefcase >}} Data Analyst & BI Dev. (Stage)

{{< fa building >}} **Safran Seats**

{{< fa calendar-days >}} 04/2023 -- 08/2023

{{< fa location-dot >}} *Issoudun, France*

Solution **python** (créée avec `typer`) permettant d'analyser la qualité et la cohérence des données entre différentes bases de données (logiciel SIRH, ERP, PLM), destiné à l'usage de l'équipe *Data* pour des sujets de gouvernance de données.

Migration de tables, vues et procédures stockées de SQL Server vers Snowflake dans le cadre de la nouvelle infrastructure de **Data Warehousing**.

Création d'un Dashboard PowerBI d'analyse du *lead time* et de suivi des ordres de fabrication pour la Supply Chain $\rightarrow$ **Ce rapport a notamment permis d'identifier les ordres de fabrication bloqués et les a considérablement réduit.**

Elaboration d'un dashboard pour le service HSE permettant de suivre le taux de fréquence des accidents sur site, entre autres KPI $\rightarrow$ **Ce rapport a permis d'éviter une trentaine d'heures par mois de traitement manuel, en plus d'en faciliter la diffusion.**

Déploiement, suivi et gestion des demandes d'évolution de plus de 4 tableaux de bord sur le PowerBI Report Server de Safran. 

:::
:::
:::

::: {.timeline-event}
::: {.timeline-point .bg_4}
:::
::: {.timeline-content}
::: {.timeline-border .bg_4}
:::
::: {.timeline-description}

## {{< fa briefcase >}} Data Analyst

{{< fa building >}} **Crédit Agricole Titres**

{{< fa calendar-days >}} 06/2022 -- 08/2022

{{< fa location-dot >}} *Mer, France*

Création d'un Dashboard pour le service de Mobilité Bancaire.

Développement d'un système de priorisation des boîtes mail partagées en utilisant `VBA`.

Automatisation d'exports multi-fichiers Word vers du PDF.

:::
:::
:::

::: {.timeline-event}
::: {.timeline-point .bg_5}
:::
::: {.timeline-content}
::: {.timeline-border .bg_5}
:::
::: {.timeline-description}

## {{< fa graduation-cap >}} Master Data Science / Business Econ. (Mécen)

{{< fa calendar-days >}} 2022 -- 2024

{{< fa location-dot >}} *Université de Tours, France*


:::
:::
:::


::: {.timeline-event}
::: {.timeline-point .bg_6}
:::
::: {.timeline-content}
::: {.timeline-border .bg_6}
:::
::: {.timeline-description}

## {{< fa graduation-cap >}} Licence d'économie

{{< fa calendar-days >}} 2018 -- 2022

{{< fa location-dot >}} *Université de Tours, France*


:::
:::
:::

:::