name: Get Current Date

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date
        id: get_date
        run: |
          # Get the current date in DD/MM/YYYY format
          CURRENT_DATE=$(date '+%d/%m/%Y')
          echo "Current Date: $CURRENT_DATE"
          echo "CURRENT_DATE=$CURRENT_DATE" >> $GITHUB_ENV

      - name: Write the current date to date.yml
        run: |
          echo "date: ${{ env.CURRENT_DATE }}" > utils/date.yml

      - name: Check if there are changes
        id: check_changes
        run: |
          git diff --quiet || echo "changes"
        
      - name: Commit date.yml
        if: steps.check_changes.outputs.changes == 'changes'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add utils/date.yml
          git commit -m "🔄 Update current date to: ${{ env.CURRENT_DATE }}."
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
